import sqlite3

auth = sqlite3.connect('application1.db')
a = auth.cursor()
a.execute('''CREATE TABLE Applications(APPLICATION_ID INTEGER PRIMARY KEY AUTOINCREMENT,APPLIED_COUNTRY VARCHAR(20) NOT NULL,NAME VARCHAR(20) NOT NULL,AGE INT NOT NULL,PHONE_NUMBER INT NOT NULL,EMAIL_ADD VARCHAR(40) NOT NULL)''')
print('DONE ')